// packages/storybook-angular/src/renderers/app/inline-linked-struct-field-renderer.component.ts
import { Component, Inject, ChangeDetectorRef } from '@angular/core';
import {
  IInlineLinkedStructFieldRenderer,
  createCssClass,
} from '@de-re-crud/ui';
import { NgRenderer } from '@de-re-crud/angular';

@Component({
  selector: 'drc-inline-linked-struct-field-renderer',
  templateUrl: './inline-linked-struct-field-renderer.component.html',
})
export class InlineLinkedStructFieldRenderer extends NgRenderer<
  IInlineLinkedStructFieldRenderer
> {
  constructor(@Inject(ChangeDetectorRef) changeDetectorRef: ChangeDetectorRef) {
    super(changeDetectorRef);
  }

  getCssName = (...names: string[]) => {
    return createCssClass(
      'de-re-crud-angular-inline-linked-struct-field-renderer',
      ...names,
    );
  };
}

<div [ngClass]="getCssName()">
    <div [ngClass]="getCssName('controls')">
        <label [htmlFor]="props.rendererId">
            <span>{{props.label}}</span>
            <span *ngIf="props.required" class="required text-danger"> *</span>
        </label>
        <span>&nbsp;</span>
        <button *ngIf="props.canAdd()"
                type="button"
                class="btn btn-sm btn-secondary"
                [disabled]="props.disabled"
                (click)="props.onAdd()">
            Add
        </button>
    </div>
    <div [ngClass]="getCssName('items')">
        <span *ngIf="!props.renderedItems.length">None</span>

        <div *ngFor="let item of props.renderedItems; let i = index;" [ngClass]="getCssName('items')">
            <drc-jsx-host [formId]="props.formId" [element]="item"></drc-jsx-host>

            <button *ngIf="props.canRemove(i)"
                    type="button"
                    class="btn btn-sm btn-danger"
                    (click)="props.onRemove(i)"
                    [disabled]="props.disabled || props.disabledRenderedItems[i]">
                Remove
            </button>

            <hr *ngIf="props.canRemove(i)" />
        </div>
    </div>
</div>

// packages/renderer-bootstrap4/renderers/inline-linked-struct-field-renderer.tsx
import { IInlineLinkedStructRenderer } from '@de-re-crud/core/models/renderers';
import createCssClass from '@de-re-crud/core/utils/create-css-class';
import Bootstrap4ButtonRenderer from '@de-re-crud/renderer-bootstrap4/renderers/button-renderer';
import Bootstrap4LabelRenderer from '@de-re-crud/renderer-bootstrap4/renderers/label-renderer';
import { h } from 'preact';

const cssName = 'bootstrap4-inline-linked-struct-renderer';

const Bootstrap4InlineLinkedStructFieldRenderer = ({
  label,
  required,
  disabled,
  renderedItems,
  disabledRenderedItems,
  canAdd,
  canRemove,
  onAdd,
  onRemove,
}: IInlineLinkedStructRenderer) => {
  const rows = renderedItems.map((item, index) => {
    const removeButtonVisible = canRemove(index);

    return (
      <div className={createCssClass(cssName, 'item')}>
        {item}
        {removeButtonVisible && (
          <Bootstrap4ButtonRenderer
            classes="btn btn-sm btn-danger"
            text="Remove"
            onClick={() => onRemove(index)}
            disabled={disabled || disabledRenderedItems[index]}
          />
        )}
        {removeButtonVisible && <hr />}
      </div>
    );
  });

  return (
    <div className={createCssClass(cssName)}>
      <div className={createCssClass(cssName, 'controls')}>
        <Bootstrap4LabelRenderer fieldRequired={required}>
          {label}
        </Bootstrap4LabelRenderer>{' '}
        {canAdd() && (
          <Bootstrap4ButtonRenderer
            classes="btn btn-sm btn-secondary"
            text="Add"
            onClick={onAdd}
            disabled={disabled}
          />
        )}
      </div>
      <div className={createCssClass(cssName, 'items')}>
        {!rows.length ? <span>None</span> : rows}
      </div>
    </div>
  );
};

export default Bootstrap4InlineLinkedStructFieldRenderer;
