// packages/renderer-bootstrap4/renderers/table-linked-struct-field-renderer.tsx
import { ITableLinkedStructRenderer } from '@de-re-crud/core/models/renderers';
import createCssClass from '@de-re-crud/core/utils/create-css-class';
import { h } from 'preact';
import Bootstrap4ButtonRenderer from './button-renderer';
import Bootstrap4LabelRenderer from './label-renderer';

const cssName = 'bootstrap4-table-linked-struct-renderer';

const Bootstrap4TableLinkedStructFieldRenderer = ({
  label,
  required,
  headers,
  busy,
  value,
  valueErrorIndicators,
  canAdd,
  canRemove,
  onAdd,
  onEdit,
  onRemove
}: ITableLinkedStructRenderer) => {
  const rows = [];

  value.forEach((columns, index) => {
    const removeButtonVisible = canRemove(index);

    rows.push(
      <tr className={valueErrorIndicators[index] && 'table-danger'}>
        {columns.map((x) => (
          <td>{x || ' '}</td>
        ))}
        <td>
          <div className={createCssClass(cssName, 'row', 'actions')}>
            <Bootstrap4ButtonRenderer
              classes="btn btn-link"
              text="Edit"
              onClick={() => onEdit(index)}
            />
            {removeButtonVisible && <span>|</span>}
            {removeButtonVisible && (
              <Bootstrap4ButtonRenderer
                classes="btn btn-link"
                text="Remove"
                onClick={() => onRemove(index)}
              />
            )}
          </div>
        </td>
      </tr>
    );
  });

  return (
    <div className={createCssClass(cssName)}>
      <div className={createCssClass(cssName, 'controls')}>
        <Bootstrap4LabelRenderer fieldRequired={required}>
          {label}
        </Bootstrap4LabelRenderer>{' '}
        {canAdd() && (
          <Bootstrap4ButtonRenderer
            classes="btn btn-sm btn-secondary"
            text="Add"
            onClick={onAdd}
            disabled={busy}
          />
        )}
      </div>
      <table className="table table-bordered table-sm">
        <thead>
          <tr>
            {headers.map((header) => (
              <th key={header}>{header}</th>
            ))}
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody>
          {!rows.length ? (
            <tr>
              <td colSpan={100}>None</td>
            </tr>
          ) : (
            rows
          )}
        </tbody>
      </table>
    </div>
  );
};

export default Bootstrap4TableLinkedStructFieldRenderer;

// packages/storybook-angular/src/renderers/app/table-linked-struct-field-renderer.component.ts
import { Component } from '@angular/core';
import {
  ITableLinkedStructFieldRenderer,
  createCssClass,
} from '@de-re-crud/ui';
import { NgRenderer } from '@de-re-crud/angular/public-api';

interface IRow {
  columns: string[];
}

@Component({
  selector: 'drc-table-linked-struct-field-renderer',
  templateUrl: './table-linked-struct-field-renderer.component.html',
})
export class TableLinkedStructFieldRenderer extends NgRenderer<
  ITableLinkedStructFieldRenderer
> {
  get rows(): IRow[] {
    const value: IRow[] = [];

    this.props.value.forEach((columns) => {
      value.push({
        columns: columns.map((x) => x || ' '),
      });
    });

    return value;
  }

  getCssName = (...names: string[]) => {
    return createCssClass(
      'de-re-crud-angular-table-linked-struct-ifled-renderer',
      ...names,
    );
  };

  onAdd = () => {
    this.props.onAdd();
  };

  onEdit = (index: number) => {
    this.props.onEdit(index);
  };

  onRemove = (index: number) => {
    this.props.onRemove(index);
  };
}

<div [ngClass]="getCssName()">
    <div [ngClass]="getCssName('controls')">
        <label>
            <span>{{props.label}}</span>
            <span *ngIf="props.required" class="required text-danger"> *</span>
            <span>&nbsp;</span>
            <button
                *ngIf="props.canAdd()"
                type="button"
                class="btn btn-sm btn-secondary"
                [disabled]="props.disabled"
                (click)="onAdd()">
                Add
            </button>
        </label>
    </div>

    <table class="table table-bordered table-sm">
        <thead>
            <tr>
                <th *ngFor="let header of props.headers">{{header}}</th>
                <th>&nbsp;</th>
            </tr>
        </thead>

        <tbody>
            <tr *ngIf="!rows.length">
              <td colspan="100">None</td>
            </tr>
            <tr *ngFor="let row of rows; let i = index;" [ngClass]="{ 'table-danger': props.valueErrorIndicators[i] }">
                <td *ngFor="let column of row.columns">{{column}}</td>
                <td>
                    <div [ngClass]="getCssName('row', 'actions')">
                        <button 
                            type="button"
                            class="btn btn-link"
                            (click)="onEdit(i)"
                            [disabled]="props.disabledValues[i]">
                            Edit
                        </button>
                        <span *ngIf="props.canRemove(i)">|</span>
                        <button
                            *ngIf="props.canRemove(i)"
                            type="button"
                            class="btn btn-link"
                            (click)="onRemove(i)"
                            [disabled]="props.disabled || props.disabledValues[i]">
                            Remove
                        </button>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
