// packages/storybook-ui/src/renderers/tree-renderer.tsx
import {
  createCssClass,
  h,
  ITableLinkedStructFieldRenderer,
} from '@de-re-crud/ui';
import {
  Bootstrap4ButtonRenderer,
  Bootstrap4LabelRenderer,
} from '@de-re-crud/theme-bootstrap4';

const cssName = 'tree-renderer';

const TreeRenderer = ({
  label,
  required,
  headers,
  disabled,
  value,
  valueErrorIndicators,
  disabledValues,
  canAdd,
  canRemove,
  onAdd,
  onEdit,
  onRemove,
  hints,
  renderChildField,
}: ITableLinkedStructFieldRenderer) => {
  const rows = [];

  value.forEach((columns, index) => {
    const removeButtonVisible = canRemove(index);

    rows.push(
      <tr className={valueErrorIndicators[index] && 'table-danger'}>
        {columns.map((x) => (
          <td>{x || ' '}</td>
        ))}
        <td>
          <div className={createCssClass(cssName, 'row', 'actions')}>
            <Bootstrap4ButtonRenderer
              classes="btn btn-link"
              text="Edit"
              onClick={() => onEdit(index)}
              disabled={disabledValues[index]}
            />
            {removeButtonVisible && <span>|</span>}
            {removeButtonVisible && (
              <Bootstrap4ButtonRenderer
                classes="btn btn-link"
                text="Remove"
                onClick={() => onRemove(index)}
                disabled={disabled || disabledValues[index]}
              />
            )}
          </div>
        </td>
      </tr>,
      <tr>
        <td colSpan={columns.length + 1}>
          {renderChildField(index, (hints as any).childKey)}
        </td>
      </tr>,
    );
  });

  return (
    <div className={createCssClass(cssName)}>
      <div className={createCssClass(cssName, 'controls')}>
        <Bootstrap4LabelRenderer fieldRequired={required}>
          {label}
        </Bootstrap4LabelRenderer>{' '}
        {canAdd() && (
          <Bootstrap4ButtonRenderer
            classes="btn btn-sm btn-secondary"
            text="Add"
            onClick={() => onAdd(undefined, false)}
            disabled={disabled}
          />
        )}
      </div>
      <table className="table table-bordered table-sm">
        <thead>
          <tr>
            {headers.map((header) => (
              <th>{header}</th>
            ))}
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody>
          {!rows.length ? (
            <tr>
              <td colSpan={100}>None</td>
            </tr>
          ) : (
            rows
          )}
        </tbody>
      </table>
    </div>
  );
};
export default TreeRenderer;

// packages/storybook-angular/src/renderers/app/tree-renderer.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Inject,
} from '@angular/core';
import { TableLinkedStructFieldRenderer } from './table-linked-struct-field-renderer.component';

@Component({
  selector: 'drc-tree',
  templateUrl: './tree-renderer.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeRenderer extends TableLinkedStructFieldRenderer {
  constructor(@Inject(ChangeDetectorRef) changeDetectorRef: ChangeDetectorRef) {
    super(changeDetectorRef);
  }
}

<div [ngClass]="getCssName()">
    <div [ngClass]="getCssName('controls')">
        <label>
            <span>{{props.label}}</span>
            <span *ngIf="props.required" class="required text-danger"> *</span>
            <span>&nbsp;</span>
            <button
                    *ngIf="props.canAdd()"
                    type="button"
                    class="btn btn-sm btn-secondary"
                    [disabled]="props.disabled"
                    (click)="props.onAdd()">
                Add
            </button>
        </label>
    </div>

    <table class="table table-bordered table-sm">
        <thead>
        <tr>
            <th *ngFor="let header of props.headers">{{header}}</th>
            <th>&nbsp;</th>
        </tr>
        </thead>

        <tbody>
        <tr *ngIf="!rows.length">
            <td colspan="100">None</td>
        </tr>
        <tr *ngFor="let row of rows; let i = index;" [ngClass]="{ 'table-danger': props.valueErrorIndicators[i] }">
            <td *ngFor="let column of row.columns">{{column}}</td>
            <td>
                <div [ngClass]="getCssName('row', 'actions')">
                    <button
                            type="button"
                            class="btn btn-link"
                            (click)="props.onEdit(i)"
                            [disabled]="props.disabledValues[i]">
                        Edit
                    </button>
                    <span *ngIf="props.canRemove(i)">|</span>
                    <button
                            *ngIf="props.canRemove(i)"
                            type="button"
                            class="btn btn-link"
                            (click)="props.onRemove(i)"
                            [disabled]="props.disabled || props.disabledValues[i]">
                        Remove
                    </button>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
