// packages/ui/form/index.tsx
import { FieldValue, ObjectFieldValue } from '@de-re-crud/core';
import Logger from '@de-re-crud/core/logger';
import { formPathToValue } from '@de-re-crud/core/utils';
import { Provider } from 'redux-zero/preact';
import { h, render } from '../h';
import BaseComponent from '../renderers/base-component';
import { createStore, IStore, updateStore } from '../store';
import shallowCompare from '../renderers/utils/shallow-compare';
import generateCacheKey from '../renderers/utils/generate-cache-key';
import FormConnect from './form.connect';
import { IFormConnectProps as IFormProps } from './form.props';

export {
  FormSubmission,
  FormSubmissionCallback,
  FieldChangeNotification,
  FieldChangeNotificationType,
  FieldChangeNotificationCallback,
  IFieldChangeNotificationParams,
  FieldParentChangeNotification,
  FieldParentChangeNotificationCallback,
  IFieldParentChangeNotificationParams,
  IFieldChangeNotificationCallbackParams,
  FormType,
} from './form.props';

export { IFormProps };

export interface IForm {
  reEvaluateConditions: () => void;
  setValue: (path: string, value?: FieldValue) => void;
}

export function renderForm(props: IFormProps, nativeElement: Element): IForm {
  let form: Form;

  render(
    <Form
      ref={(c) => {
        form = c;
      }}
      {...props}
    />,
    null,
    nativeElement,
  );

  return {
    reEvaluateConditions: () => {
      form.reEvaluateConditions();
    },
    setValue: (path: string, value?: FieldValue) => {
      form.setValue(path, value);
    },
  };
}

export default class Form extends BaseComponent<IFormProps> {
  private store: IStore;

  constructor(props: IFormProps) {
    super(props);

    const {
      block,
      collectionReferences,
      disabled,
      initialErrors,
      onCancel,
      onFieldChange,
      onFieldChangeInputTimeout,
      onFieldChangeType,
      onFieldParentChange,
      onSubmit,
      renderers,
      rendererOptions,
      buttonOptions,
      struct,
      schema,
      type,
      initialValue,
    } = props;

    this.store = createStore(
      schema,
      struct,
      type,
      block,
      disabled,
      rendererOptions,
      renderers,
      buttonOptions,
      collectionReferences,
      initialErrors,
      initialValue,
      onSubmit,
      onCancel,
      onFieldChange,
      onFieldChangeInputTimeout,
      onFieldChangeType,
      onFieldParentChange,
    );

    this.reEvaluateConditions = this.reEvaluateConditions.bind(this);
    this.setValue = this.setValue.bind(this);
  }

  public shouldComponentUpdate(nextProps: IFormProps) {
    return shallowCompare(this, nextProps);
  }

  public componentWillReceiveProps(nextProps: IFormProps) {
    updateStore(
      this.store,
      nextProps.disabled,
      nextProps.rendererOptions,
      nextProps.renderers,
      nextProps.buttonOptions,
      nextProps.collectionReferences,
      nextProps.onSubmit,
      nextProps.onCancel,
      nextProps.onFieldChange,
      nextProps.onFieldChangeInputTimeout,
      nextProps.onFieldChangeType,
      nextProps.onFieldParentChange,
    );
  }

  public reEvaluateConditions() {
    this.store.setState({
      conditionCacheKey: generateCacheKey(),
    });
  }

  public getValue(path: string) {
    if (!path) {
      Logger.warning('No path set. Can not get value.');
      return undefined;
    }

    const { value } = this.store.getState();

    return formPathToValue(value, path);
  }

  public setValue(path: string, value?: FieldValue | null) {
    if (!path) {
      Logger.warning('No path set. Can not set value.');
      return;
    }

    if (typeof value === 'undefined') {
      value = null;
    }

    const { value: formValue } = this.store.getState();
    const newFormValue = { ...formValue };

    const pathArray = path.split('.');

    let currentValue: ObjectFieldValue = newFormValue;
    let parentValue: ObjectFieldValue;

    for (let i = 0; i < pathArray.length; i++) {
      const currentPath = pathArray[i];
      parentValue = currentValue;

      if (i === pathArray.length - 1) {
        parentValue[currentPath] = value;
        break;
      }

      if (Array.isArray(currentValue)) {
        parentValue[currentPath] = currentValue.concat();
      } else if (typeof currentValue === 'object') {
        parentValue[currentPath] = { ...currentValue };
      }

      currentValue = parentValue[currentPath];
    }

    this.store.setState({
      value: newFormValue,
    });
  }

  public render() {
    return (
      <Provider store={this.store}>
        <FormConnect />
      </Provider>
    );
  }
}

// packages/angular/src/form.component.ts
import {
  Component,
  ViewChild,
  OnChanges,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  AfterViewInit,
} from '@angular/core';
import { FieldValue, ICollectionReferences, IErrors } from '@de-re-crud/core';
import {
  IButtonOptions,
  IRendererOptions,
  IRendererDefinitions,
  IForm,
  IFieldChangeNotificationParams,
  IFieldParentChangeNotificationParams,
  renderForm,
  FormSubmissionCallback,
  FieldChangeNotificationType,
  FormType,
  FieldChangeNotificationCallback,
  FieldParentChangeNotificationCallback,
} from '@de-re-crud/ui';
import { JsxHostDirective } from './jsx-host.directive';
import {
  IFieldParentChangeEvent,
  IFormSubmission,
  IFieldChangeEvent,
} from './form-submission';

@Component({
  selector: 'drc-form',
  template: `
    <div class="de-re-crud-angular-form" drcJsxHost></div>
  `,
  styles: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FormComponent implements AfterViewInit, OnChanges, IForm {
  private instance: IForm;

  @ViewChild(JsxHostDirective, { static: false })
  jsxHost: JsxHostDirective;

  @Input()
  type?: FormType;

  @Input()
  cancelVisible: boolean;

  @Input()
  cssClass?: string;

  @Input()
  schema: any;

  @Input()
  struct: string;

  @Input()
  block?: string;

  @Input()
  disabled?: boolean;

  @Input()
  initialErrors?: IErrors;

  @Input()
  initialValue?: any;

  @Input()
  collectionReferences?: ICollectionReferences;

  @Input()
  renderers?: Partial<IRendererDefinitions>;

  @Input()
  rendererOptions?: IRendererOptions;

  @Input()
  buttonOptions?: IButtonOptions;

  @Input()
  fieldChangeInputTimeout?: number;

  @Input()
  fieldChangeType?: FieldChangeNotificationType;

  @Input()
  asyncFieldParentChanges = false;

  @Output()
  fieldChanged = new EventEmitter<IFieldChangeEvent>();

  @Input()
  asyncFieldChanges = false;

  @Output()
  fieldParentChanged = new EventEmitter<IFieldParentChangeEvent>();

  @Output()
  canceled = new EventEmitter();

  @Output()
  submitted = new EventEmitter<IFormSubmission>();

  ngAfterViewInit() {
    this.render();
  }

  ngOnChanges() {
    this.render();
  }

  onFieldChange = (params: IFieldChangeNotificationParams) => {
    const event: IFieldChangeEvent = {
      params,
    };

    this.fieldChanged.emit(event);
  };

  onFieldChangeAsync = (
    params: IFieldChangeNotificationParams,
    cb: FieldChangeNotificationCallback,
  ) => {
    const event: IFieldChangeEvent = {
      params,
      onComplete: cb,
    };

    this.fieldChanged.emit(event);
  };

  onFieldParentChange = (params: IFieldParentChangeNotificationParams) => {
    const event: IFieldParentChangeEvent = {
      params,
    };

    this.fieldParentChanged.emit(event);
  };

  onFieldParentChangeAsync = (
    params: IFieldParentChangeNotificationParams,
    cb: FieldParentChangeNotificationCallback,
  ) => {
    const event: IFieldParentChangeEvent = {
      params,
      onComplete: cb,
    };

    this.fieldParentChanged.emit(event);
  };

  onCancel = () => {
    this.canceled.emit();
  };

  onSubmit = (value: any, cb: FormSubmissionCallback) => {
    this.submitted.emit({
      value,
      onComplete: cb,
    });
  };

  reEvaluateConditions = () => {
    this.instance.reEvaluateConditions();
  };

  getValue = (path?: string) => {
    return this.instance.getValue(path);
  };

  setValue = (path: string, value?: FieldValue, errors?: string[]) => {
    this.instance.setValue(path, value, errors);
  };

  setErrors(path: string, errors: string[]) {
    this.instance.setErrors(path, errors);
  }

  render() {
    if (!this.jsxHost) {
      return;
    }

    const { nativeElement } = this.jsxHost.viewContainerRef.element;

    this.instance = renderForm(
      {
        type: this.type,
        className: this.cssClass,
        schema: this.schema,
        struct: this.struct,
        block: this.block,
        disabled: this.disabled,
        onCancel: this.cancelVisible ? this.onCancel : undefined,
        onFieldChangeInputTimeout: this.fieldChangeInputTimeout,
        onFieldChangeType: this.fieldChangeType,
        onFieldChange: this.asyncFieldChanges
          ? this.onFieldChangeAsync
          : this.onFieldChange,
        onFieldParentChange: this.asyncFieldParentChanges
          ? this.onFieldParentChangeAsync
          : this.onFieldParentChange,
        onSubmit: this.onSubmit,
        renderers: this.renderers,
        rendererOptions: this.rendererOptions,
        buttonOptions: this.buttonOptions,
        collectionReferences: this.collectionReferences,
        initialErrors: this.initialErrors,
        initialValue: this.initialValue,
      },
      nativeElement,
    );
  }
}
